"""empty message

Revision ID: 29bf7f26b1d9
Revises: 737272d633d9
Create Date: 2021-08-18 21:27:11.883371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29bf7f26b1d9'
down_revision = '737272d633d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('photo', sa.String(length=255), nullable=True))
    op.add_column('book', sa.Column('rented', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'rented')
    op.drop_column('book', 'photo')
    # ### end Alembic commands ###
