"""empty message

Revision ID: 9dd01b307670
Revises: 29bf7f26b1d9
Create Date: 2021-08-19 22:08:10.937894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dd01b307670'
down_revision = '29bf7f26b1d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('user_name', sa.String(length=30), nullable=False))
    op.alter_column('comment', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'user', ['user_name'], ['username'], ondelete='CASCADE')
    op.drop_column('comment', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('user_id', sa.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['email'], ondelete='CASCADE')
    op.alter_column('comment', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_column('comment', 'user_name')
    # ### end Alembic commands ###
